## ONNX Runtime 으로 Lenet-1 모델 돌리기
- lenet-1_tanh.onnx 모델 로드 및 Inference 진행
- mnist Data 이용, Train, Test 진행
- 사전 학습 완료된 파일 : lenet-1_tanh.onnx
    

In [1]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras import utils
from PIL import Image

# image resize 함수
def img_resize(value, img_array):
    print("--images are being resizing--")
    result = np.zeros((len(img_array), value[0], value[1]))

    for index in range(len(img_array)):
        img = Image.fromarray(img_array[index], 'L')
        img = img.resize((value[0], value[1]))
        img = np.array(img)
        result[index] = img
    print("--image resize complete--")
    return result

# mnist Data Load 및
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()
print(type(X_train))
input_shape = (28, 28)

# data resize
X_train = img_resize(input_shape, X_train)
X_test = img_resize(input_shape, X_test)
print('data resize ',X_train.shape, X_test.shape)

# 차원 확장
X_train = np.expand_dims(X_train, axis = -1)
X_test = np.expand_dims(X_test, axis = -1)
print('expand_dims ',X_train.shape, X_test.shape)

# 정답값 categorical로
Y_train = utils.to_categorical(Y_train, 10)
Y_test = utils.to_categorical(Y_test, 10)
print('to_categorical ',X_train.shape, X_test.shape)

print('전처리 작업 완료')

<class 'numpy.ndarray'>
--images are being resizing--
--image resize complete--
--images are being resizing--
--image resize complete--
data resize  (60000, 28, 28) (10000, 28, 28)
expand_dims  (60000, 28, 28, 1) (10000, 28, 28, 1)
to_categorical  (60000, 28, 28, 1) (10000, 28, 28, 1)
전처리 작업 완료


In [4]:
# ONNX Runtime 완료
import onnxruntime as rt
sess = rt.InferenceSession("../model/lenet-1.onnx")

input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name

# sess.run
pred_onx = sess.run([label_name], {input_name: X_test.astype(np.float32)})[0]

print('---------- y_pred ----------')
print(pred_onx)
print('---------- y_test ----------')
print(Y_test)

---------- y_pred ----------
[[0.07794993 0.05165108 0.08002709 ... 0.31299546 0.08149029 0.22448838]
 [0.04747117 0.127508   0.09949815 ... 0.03117068 0.15714328 0.04951626]
 [0.05254303 0.20967631 0.10641795 ... 0.10804937 0.11799269 0.06083203]
 ...
 [0.07503749 0.0896731  0.07930425 ... 0.07025807 0.08827303 0.15249032]
 [0.13246968 0.10729677 0.04677816 ... 0.08805109 0.12177698 0.12704699]
 [0.08469986 0.03206249 0.10723868 ... 0.04446852 0.06137119 0.06106744]]
---------- y_test ----------
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [5]:
# 정확도 보기
from sklearn.metrics import accuracy_score

# 테스트 predict 결과들 비교 (평가지표 보기위함)
pred = np.round(np.array(pred_onx).flatten().tolist())
test = np.array(np.array(Y_test).flatten().tolist())

k_accuracy = float(accuracy_score(test, pred))
print(k_accuracy)

0.90044
